### ISSUE TITLE
运行jrender demo时报错

### ISSUE THREAD

**Issue by yuyuyu223** [Jittor/jrender#12]
Caught segfault at address 0, thread_name: '', flush log...
[i 0622 16:16:54.348247 64 tracer.cc:149] stack trace for pid= 475875
[New LWP 477059]
[New LWP 477063]
[New LWP 477064]
[New LWP 481746]
[New LWP 481749]
[New LWP 481752]
[New LWP 481775]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fae6362dcaf in __GI___wait4 (pid=487229, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[Current thread is 1 (Thread 0x7fae633e2740 (LWP 475875))]
#0  0x00007fae6362dcaf in __GI___wait4 (pid=487229, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007fae6062b897 in jittor::print_trace() () from /space0/yuhc/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.5/Linux-5.13.0-4xcd/IntelRXeonRCPUxd5/default/jit_utils_core.cpython-38-x86_64-linux-gnu.so
#2  0x00007fae60627625 in jittor::segfault_sigaction(int, siginfo_t*, void*) () from /space0/yuhc/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.5/Linux-5.13.0-4xcd/IntelRXeonRCPUxd5/default/jit_utils_core.cpython-38-x86_64-linux-gnu.so
#3  <signal handler called>
#4  0x00007fae41050660 in ssymm_iltcopy_HASWELL () from /space0/yuhc/miniconda3/envs/jittor/lib/python3.8/site-packages/numpy/core/../../numpy.libs/libopenblas64_p-r0-2f7c42d4.3.18.so
#5  0x00007fad27129806 in dtrtri_ () from /space0/yuhc/miniconda3/envs/jittor/lib/python3.8/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-8b9e111f.3.17.so
#6  0x00007fad284c0d68 in dgetri_ () from /space0/yuhc/miniconda3/envs/jittor/lib/python3.8/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-8b9e111f.3.17.so
#7  0x00007fae2d9f3221 in f2py_rout__flapack_dgetri (capi_self=<optimized out>, capi_args=<optimized out>, capi_keywds=<optimized out>, f2py_func=0x7fad284c0c30 <dgetri_>) at build/src.linux-x86_64-3.8/build/src.linux-x86_64-3.8/scipy/linalg/_flapackmodule.c:8997
#8  0x0000556e1124785f in _PyObject_MakeTpCall (callable=0x7fae481e2330, args=<optimized out>, nargs=<optimized out>, keywords=<optimized out>) at /tmp/build/80754af9/python_1599203911753/work/Objects/call.c:159
[e 0622 16:17:05.266688 64 log.cc:246] Caught SIGCHLD. Maybe out of memory, please reduce your worker size. si_errno: 0 si_code: 3 si_status: 11 , quick exit

**Comment by yuyuyu223** [comment]
把import numpy as np放到import jittor as jt前，成功解决
import jittor as jt也必须放到import jrender as jr之前才能正常讲Var换回cpu
