### ISSUE TITLE
运行官方Demo5和Demo6报错

### ISSUE THREAD

**Issue by SaintZhao** [Jittor/jrender#17]
E:\Game_Dev\jrender>python demo5-optim_metallic_textures.py
[i 0811 16:45:08.444000 40 compiler.py:955] Jittor(1.3.5.4) src: c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0811 16:45:08.512000 40 compiler.py:956] cl at C:\Users\saintzhao\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0811 16:45:08.513000 40 compiler.py:957] cache_path: C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default
[i 0811 16:45:08.611000 40 install_cuda.py:88] cuda_driver_version: [10, 2, 0]
[i 0811 16:45:09.520000 40 __init__.py:411] Found C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe(10.2.89) at C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe.
[i 0811 16:45:09.635000 40 compiler.py:1010] cuda key:cu10.2.89
[i 0811 16:45:09.636000 40 __init__.py:227] Total mem: 63.78GB, using 16 procs for compiling.
[i 0811 16:45:12.757000 40 jit_compiler.cc:28] Load cc_path: C:\Users\saintzhao\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0811 16:45:12.759000 40 init.cc:62] Found cuda archs: [75,]
[i 0811 16:45:13.729000 40 compile_extern.py:517] mpicc not found, distribution disabled.
[i 0811 16:45:22.033000 40 cuda_flags.cc:32] CUDA enabled.
Optimizing:   0%|                                                                               | 0/20 [00:00<?, ?it/s][e 0811 16:45:27.211000 40 log.cc:565] cl : Command line warning D9025 : overriding '/EHa' with '/EHs'
code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cccl : Command line warning D9025 : overriding '/EHa' with '/EHs'
code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.ccC:/Users/saintzhao/.cache/jittor/jt1.3.5/cl/py3.10.6/Windows-10-10.xcc/IntelRCoreTMi7xff/default/cu10.2.89/jit/code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc(162): error: function "atomicAdd(double *, double)" has already been defined

1 error detected in the compilation of "C:/Users/SAINTZ~1/AppData/Local/Temp/tmpxft_00020d5c_00000000-8_code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cpp4.ii".
code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc
Optimizing:   0%|                                                                               | 0/20 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "E:\Game_Dev\jrender\demo5-optim_metallic_textures.py", line 79, in <module>
    main()
  File "E:\Game_Dev\jrender\demo5-optim_metallic_textures.py", line 72, in main
    image = images.numpy()[0].transpose((1, 2, 0))
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.numpy)).

Types of your inputs are:
 self   = Var,
 args   = (),

The function declarations are:
 ArrayArgs fetch_sync()

Failed reason:[f 0811 16:45:27.212000 40 parallel_compiler.cc:329] Error happend during compilation:
 [Error] source file location:C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89\jit\code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc
Compile operator(61/71)failed:Op(1208:4:1:1:i6:o2:s0,code->...)

Reason: [f 0811 16:45:27.212000 40 log.cc:608] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe" "C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89\jit\code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc"            -shared  -L"c:\users\saintzhao\appdata\local\programs\python\python310\libs" -lpython310  -Xcompiler -EHa -Xcompiler -MD -Xcompiler -utf-8   -I"C:\Users\saintzhao\.cache\jittor\msvc\VC\include" -I"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX  -L"C:\Users\saintzhao\.cache\jittor\msvc\VC\lib" -L"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\lib\um\x64" -L"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\lib\ucrt\x64"  -I"c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor\src" -I"c:\users\saintzhao\appdata\local\programs\python\python310\include" -DHAS_CUDA -DIS_CUDA -I"C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\include" -I"c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor\extern\cuda\inc"  -lcudart -L"C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\lib\x64" -L"C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin"  -I"C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89" -L"C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89" -L"C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default"  -l"jit_utils_core.cp310-win_amd64"  -l"jittor_core.cp310-win_amd64"  -x cu --cudart=shared -ccbin="C:\Users\saintzhao\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" --use_fast_math  -w  -I"c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor\extern/cuda/inc"  -arch=compute_75  -code=sm_75  -o "C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89\jit\code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.dll" -Xlinker -EXPORT:"?jit_run@CodeOp@jittor@@QEAAXXZ"

**Comment by SaintZhao** [comment]
E:\Game_Dev\jrender>python demo6-optim_roughness_textures.py
[i 0811 16:45:41.122000 56 compiler.py:955] Jittor(1.3.5.4) src: c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0811 16:45:41.186000 56 compiler.py:956] cl at C:\Users\saintzhao\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0811 16:45:41.187000 56 compiler.py:957] cache_path: C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default
[i 0811 16:45:41.283000 56 install_cuda.py:88] cuda_driver_version: [10, 2, 0]
[i 0811 16:45:41.346000 56 __init__.py:411] Found C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe(10.2.89) at C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe.
[i 0811 16:45:41.490000 56 compiler.py:1010] cuda key:cu10.2.89
[i 0811 16:45:41.491000 56 __init__.py:227] Total mem: 63.78GB, using 16 procs for compiling.
[i 0811 16:45:44.554000 56 jit_compiler.cc:28] Load cc_path: C:\Users\saintzhao\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0811 16:45:44.556000 56 init.cc:62] Found cuda archs: [75,]
[i 0811 16:45:45.768000 56 compile_extern.py:517] mpicc not found, distribution disabled.
[i 0811 16:45:54.336000 56 cuda_flags.cc:32] CUDA enabled.
Optimizing:   0%|                                                                               | 0/15 [00:00<?, ?it/s][e 0811 16:46:09.313000 56 log.cc:565] cl : Command line warning D9025 : overriding '/EHa' with '/EHs'
code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cccl : Command line warning D9025 : overriding '/EHa' with '/EHs'
code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.ccC:/Users/saintzhao/.cache/jittor/jt1.3.5/cl/py3.10.6/Windows-10-10.xcc/IntelRCoreTMi7xff/default/cu10.2.89/jit/code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc(162): error: function "atomicAdd(double *, double)" has already been defined

1 error detected in the compilation of "C:/Users/SAINTZ~1/AppData/Local/Temp/tmpxft_00009074_00000000-8_code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cpp4.ii".
code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc
Optimizing:   0%|                                                                               | 0/15 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "E:\Game_Dev\jrender\demo6-optim_roughness_textures.py", line 79, in <module>
    main()
  File "E:\Game_Dev\jrender\demo6-optim_roughness_textures.py", line 72, in main
    image = images.numpy()[0].transpose((1, 2, 0))
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.numpy)).

Types of your inputs are:
 self   = Var,
 args   = (),

The function declarations are:
 ArrayArgs fetch_sync()

Failed reason:[f 0811 16:46:09.314000 56 parallel_compiler.cc:329] Error happend during compilation:
 [Error] source file location:C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89\jit\code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc
Compile operator(61/71)failed:Op(1208:4:1:1:i6:o2:s0,code->...)

Reason: [f 0811 16:46:09.313000 56 log.cc:608] Check failed ret(2) == 0(0) Run cmd failed: "C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe" "C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89\jit\code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.cc"            -shared  -L"c:\users\saintzhao\appdata\local\programs\python\python310\libs" -lpython310  -Xcompiler -EHa -Xcompiler -MD -Xcompiler -utf-8   -I"C:\Users\saintzhao\.cache\jittor\msvc\VC\include" -I"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX  -L"C:\Users\saintzhao\.cache\jittor\msvc\VC\lib" -L"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\lib\um\x64" -L"C:\Users\saintzhao\.cache\jittor\msvc\win10_kits\lib\ucrt\x64"  -I"c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor\src" -I"c:\users\saintzhao\appdata\local\programs\python\python310\include" -DHAS_CUDA -DIS_CUDA -I"C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\include" -I"c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor\extern\cuda\inc"  -lcudart -L"C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\lib\x64" -L"C:\Users\saintzhao\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin"  -I"C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89" -L"C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89" -L"C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default"  -l"jit_utils_core.cp310-win_amd64"  -l"jittor_core.cp310-win_amd64"  -x cu --cudart=shared -ccbin="C:\Users\saintzhao\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" --use_fast_math  -w  -I"c:\users\saintzhao\appdata\local\programs\python\python310\lib\site-packages\jittor\extern/cuda/inc"  -arch=compute_75  -code=sm_75  -o "C:\Users\saintzhao\.cache\jittor\jt1.3.5\cl\py3.10.6\Windows-10-10.xcc\IntelRCoreTMi7xff\default\cu10.2.89\jit\code__IN_SIZE_6__in0_dim_4__in0_type_float32__in1_dim_4__in1_type_float32__in2_dim_4__in2____hash_895b032e4c661b83_op.dll" -Xlinker -EXPORT:"?jit_run@CodeOp@jittor@@QEAAXXZ"
